# Backend service for local testing
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: backend-node-port-svc
#   labels:
#     task: backend-node-port-svc
# spec:
#   ports:
#     - name: backend
#       port: 8000
#       nodePort: 30080
#   selector:
#     tier: backend
#   type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: backend-clusterip-svc
  labels:
    task: backend-clusterip-svc
spec:
  ports:
    - name: backend
      port: 8000
      targetPort: 8000
  selector:
    tier: backend
  type: ClusterIP
