apiVersion: v1
kind: Service
metadata:
  name: client-node-port-svc
  labels:
    task: client-node-port-svc
spec:
  ports:
    - name: client
      port: 3000
      nodePort: 30001
  selector:
    tier: client
  type: NodePort
