# Database service for local testing
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: db-node-port-svc
#   labels:
#     task: db-node-port-svc
# spec:
#   ports:
#     - name: postgres
#       port: 5432
#       nodePort: 30432
#   selector:
#     tier: database
#   type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: db-clusterip-svc
  labels:
    task: db-clusterip-svc
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    tier: database
  type: ClusterIP
